version: '3'

services:

  currency-convert:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=nbp_user
      - DATABASE_PASSWORD=nbp
      - DATABASE_NAME=nbp_currency
      - DATABASE_PORT=3306
    command: "bash run.sh"
    volumes:
    - .:/var/app

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=nbp_currency
      - MYSQL_USER=nbp_user
      - MYSQL_PASSWORD=nbp
    ports:
      - 3306:3306
