version: '3'

services:

  currency-convert:
    build: .
    restart: on-failure
    depends_on:
      - mysql_dbnbp
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql_dbnbp
      - DATABASE_USER=nbp_user
      - DATABASE_PASSWORD=nbp
      - DATABASE_NAME=nbp_currency
      - DATABASE_PORT=3306

  mysql_dbnbp:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=nbp_currency
      - MYSQL_USER=nbp_user
      - MYSQL_PASSWORD=nbp
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    security_opt:
      - seccomp:unconfined